[package]
name = "gsub"
version = "0.1.0"
authors = ["gabehardgrave <gabriel.hardgrave@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
regex = "1"
walkdir = "2"
lazy_static = "1.4.0"
ignore = "0.4"